### ISSUE TITLE
in VD 2.-1dev dedupe-rows doesn't work

### ISSUE THREAD

**Issue by Mikee-3000** [jsvine/visidata-plugins#3]
Deduplicating rows doesn't work in the pre-release. In this case the action didn't do anything, but in other cases it multiplies the rows (I can't figure out any pattern here)
![dedupe](https://user-images.githubusercontent.com/13318998/66300524-5e63c200-e8ed-11e9-9cb9-d642a2d45b53.gif)

Ctrl+E gets "no error".

**Comment by jsvine** [comment]
Hi @Mikee-3000, and thanks for flagging. Not too surprising, as these plugins have only been tested against the stable version of VisiData, but a good reminder that I should prepare them for `v2.x`.

**Comment by anjakefala** [comment]
Things are in in progress right now, so probably best to wait. =) I will help.

**Comment by Mikee-3000** [comment]
Thank you for looking into it :-) Let me know if there is anything I can do

**Comment by anjakefala** [comment]
Bumping this because we are getting ready to ship soon. =) Let me know if you want help with porting or have any questions.

**Comment by jsvine** [comment]
Thanks! I'll try porting soon and will let you know if I get confused :)

**Comment by jsvine** [comment]
I've created a new branch — [visidata-2.x](https://github.com/jsvine/visidata-plugins/tree/visidata-2.x) — for this work, and taken a first pass at updating the `dedupe` plugin: https://github.com/jsvine/visidata-plugins/blob/visidata-2.x/plugins/vddedupe.py

Seems to work overall, but the `Progress` invocation doesn't seem to be showing the percentage-progress indicator. @anjakefala: Any thoughts about what I might be doing wrong, specifically on that and/or more generally?

**Comment by saulpw** [comment]
That is weird.  Try using it as a context manager?  Though it should work when used as an iterator too.

You can also try passing `sheet=sheet` to Progress, which will tell the Progress object which sheet it should go on.

Does it say `selecting`, or another gerund, or nothing at all?

**Comment by jsvine** [comment]
@saulpw: I've now tried all those things, and I'm stumped. It shows no progress indicator at all. A couple of clues if it helps (while using Progress as a context manager and passing `sheet=vs`):

- If I shift to overriding `iterload` instead of `reload`, the progress indicators appear ... but the plugin doesn't quite work (columns aren't carried over, first row becomes the column, etc. — at least when working with a CSV).

- If, in the first line within the context manager, I insert `warning(len(vs.progresses))` the warning is set to `1`. Likewise, `vs.progressPct` increases as expected as the iterator proceeds. Together, this suggests to me that the progress is being set, and on the correct sheet, but just not displayed.

So maybe this is due to some interaction between overriding `reload` and the `statusbar` code?

Of course, your diagnosis might differ :)

**Comment by jsvine** [comment]
Oh, and my apologies @saulpw, I should have clarified: `Progess` seems to work as expected for `select-duplicate-rows` ... just not for `dedupe-rows`.

**Comment by saulpw** [comment]
Ah, I see!  I was looking in the wrong function.  Try moving the `@asyncthread` from the dedupe_rows function to the _reload function and see if that works.

**Comment by jsvine** [comment]
Thanks, that did the trick! Now working as expected in branch https://github.com/jsvine/visidata-plugins/tree/visidata-2.x 

That branch (which also updates the `normcol` plugin for v2.x) will be merged to the default branch once VisiData 2.x becomes the official stable version.

And thanks to @Mikee-3000 for raising this issue. Now closing.
