### ISSUE TITLE
vdnormcol doesn't check names for conflicts with globals

### ISSUE THREAD

**Issue by frosencrantz** [jsvine/visidata-plugins#5]
This is a feature request.  The vdnormcol plugin is very useful since it fixes column names to be referenced in any Visidata command that takes a Python express.  This seems like it should be built-in to Visidata.

However, it is possible for a column name to conflict with an existing global. For example a column with the name "time" would be left unchanged by vdnormcol, but would hide the time module.

Request: vdnormcol should also check columns against existing global names.

**Comment by jsvine** [comment]
Hi @frosencrantz, and very interesting proposal! On the one hand: Yes, conflicts with an existing global name are not ideal. On the other hand: I worry that the proposed feature would introduce two related forms of uncertainty:

- To anticipate the final column names, a user would need to know all existing global names. Currently, `vdnormcol` creates *very predictable* column names, without any need to know the current Python session state. 

- With this feature, the result of `vdnormcol` could differ depending on what commands you executed before it. Currently, `vdnormcol` results are entirely deterministic.

I don't think these are a *huge* headache, but my instinct is that the tradeoff is not worth it. Perhaps it makes sense to introduce, instead, a second/separate method that handles global-namespace conflicts?

In any case, I'm open to disagreement and to being persuaded otherwise.

Thanks again,
Jeremy

**Comment by frosencrantz** [comment]
Hi @jsvine,

Thanks for considering this.  I see what you mean about the consistent naming, and having additional constraints might not fit within in this plugin.

To me it seemed like the basic purpose of this plugin is to make column names usable in Python expressions.  So checking for conflicts with globals names would fit within that purpose.  I now realize this plugin doesn't fully do that, for example, I missed that unnamed columns remain unnamed.

This also makes me think that this seems like basic functionality that Visidata itself should have, a way to access all columns via Python expressions.   I'll suggest that as a feature request for Visidata.  If you are looking to adding new plugins, or adding additional functionality to this one, I think it would be useful to have column naming fixing plugin that allows all column names accessible via Python expressions. :)

**Comment by jsvine** [comment]
Thanks for the follow-up, @frosencrantz. It seems that we are thinking of this plugin in slightly different ways:

- You: To turn column names into usable Python expressions, with a primary goal of making *all* columns usable

- Me: To standardize column names (for its own sake) and to turn column names into usable Python expressions, with the primary goal of making column names *predictable*

Although for my own work I prefer my approach, I think both perspectives are valid. My suggested resolution would be to create, within this plugin, a second command (perhaps `normalize-col-names-valid-exprs`) that achieves your approach.

**Comment by frosencrantz** [comment]
Yes, @jsvine, that seems like it would be what I would find helpful.  I can't offer any code.  But I think that would be a useful addition.

I did requested/suggest a more generalized solution be built into Visidata in the now closed https://github.com/saulpw/visidata/issues/476 .  I think that would be useful for this plugin, too.  But `normalize-col-names-valid-exprs`  as suggested would be the most useful.
